sudo npm install jimp
sudo npm install randomstring
sudo npm install @mapbox/sphericalmercator
sudo npm install @mapbox/geo-viewport
sudo npm install threads
sudo npm install express
sudo npm install uuid4
sudo npm install winston
sudo npm install command-line-args
sudo npm install command-line-usage
sudo npm install json2csv
